from utils import colors

# Segments colors.
USERATHOST_BG = colors.ON_GREY02
USERATHOST_FG = colors.ON_GREY04

SSH_BG = colors.ON_TEAL
SSH_FG = colors.ON_GREY01

CURRENTDIR_BG = colors.ON_GREY01
CURRENTDIR_FG = colors.ON_GREY05

READONLY_BG = colors.ON_GREY01
READONLY_FG = colors.ON_RED

EXITCODE_BG = colors.ON_GREY01
EXITCODE_FG = colors.ON_RED

PADDING_BG = colors.ON_GREY00

GIT_UNTRACKED_FILES_BG = colors.ON_GREY01
GIT_UNTRACKED_FILES_FG = colors.ON_RED
GIT_CHANGES_NOT_STAGED_BG = colors.ON_GREY02
GIT_CHANGES_NOT_STAGED_FG = colors.ON_ORANGE
GIT_ALL_CHANGES_STAGED_BG = colors.ON_GREY03
GIT_ALL_CHANGES_STAGED_FG = colors.ON_YELLOW
GIT_CLEAN_BG = colors.ON_GREY01
GIT_CLEAN_FG = colors.ON_GREEN

VENV_BG = colors.ON_BLUE
VENV_FG = colors.ON_GREY00

JOBS_BG = colors.ON_PURPLE
JOBS_FG = colors.ON_GREY00

TIME_BG = colors.ON_GREY00
TIME_FG = colors.ON_GREY03